# Generated by Django 3.1.4 on 2020-12-22 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='项目编号')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('status', models.IntegerField(null=True, verbose_name='当前项目状态')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '项目基本信息表',
                'verbose_name_plural': '项目基本信息表',
                'db_table': 'tb_ProjectBaseInfo',
            },
        ),
    ]
