# Generated by Django 3.1.4 on 2020-12-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbaseinfo',
            name='is_delete',
            field=models.BooleanField(default=0, verbose_name='是否删除'),
        ),
    ]
