# Generated by Django 3.1.4 on 2020-12-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_projectbaseinfo_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbaseinfo',
            name='style',
            field=models.CharField(max_length=20, null=True, verbose_name='项目类型'),
        ),
    ]
