# Generated by Django 3.1.4 on 2020-12-23 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20201223_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbaseinfo',
            name='is_delete',
            field=models.BooleanField(default=0, help_text='逻辑删除', verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='projectbaseinfo',
            name='leader',
            field=models.ForeignKey(help_text='负责人', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='projectbaseinfo',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=20, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projectbaseinfo',
            name='status',
            field=models.IntegerField(help_text='{"0": "项目获得", "1": "项目启动", "2": "项目策划", "3": "项目实施", "4": "项目测试", "5": "项目结项", "6": "其他"}', null=True, verbose_name='当前项目状态'),
        ),
        migrations.AlterField(
            model_name='projectbaseinfo',
            name='style',
            field=models.CharField(help_text='项目类型', max_length=20, null=True, verbose_name='项目类型'),
        ),
    ]
