# Generated by Django 3.1.4 on 2020-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201223_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbaseinfo',
            name='status',
            field=models.CharField(help_text='{"0": "项目获得", "1": "项目启动", "2": "项目策划", "3": "项目实施", "4": "项目测试", "5": "项目结项", "6": "其他"}', max_length=20, null=True, verbose_name='当前项目状态'),
        ),
    ]
