# Generated by Django 3.1.4 on 2021-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210111_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebaseinfo',
            name='file_router',
            field=models.FileField(help_text='文件存储路径', upload_to='upload/%Y/%m/%d/', verbose_name='文件存储路径'),
        ),
    ]
