# Generated by Django 3.1.4 on 2021-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210111_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebaseinfo',
            name='leader',
            field=models.CharField(blank=True, help_text='审批人', max_length=50, null=True, verbose_name='审批人'),
        ),
    ]
