# Generated by Django 3.1.4 on 2021-01-11 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_filebaseinfo_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='类别编号', primary_key=True, serialize=False, verbose_name='类别编号')),
                ('status', models.CharField(help_text='{"0": "项目获得", "1": "项目启动", "2": "项目策划", "3": "项目实施", "4": "项目测试", "5": "项目结项", "6": "其他"}', max_length=20, null=True, verbose_name='当前项目状态')),
                ('project', models.ForeignKey(help_text='隶属项目', on_delete=django.db.models.deletion.CASCADE, to='pages.projectbaseinfo', verbose_name='隶属项目')),
            ],
            options={
                'verbose_name': '项目阶段表',
                'verbose_name_plural': '项目阶段表',
                'db_table': 'tb_ProjectCategory',
            },
        ),
        migrations.AlterField(
            model_name='filebaseinfo',
            name='file_project',
            field=models.ForeignKey(help_text='项目阶段', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.projectcategory', verbose_name='文档隶属项目阶段'),
        ),
    ]
