# Generated by Django 3.1.4 on 2021-01-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_remove_projectbaseinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectInfoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseinfo', models.ForeignKey(help_text='项目信息', on_delete=django.db.models.deletion.CASCADE, to='pages.projectbaseinfo', verbose_name='项目基本信息')),
                ('category', models.ForeignKey(help_text='项目分类', on_delete=django.db.models.deletion.CASCADE, to='pages.projectcategory', verbose_name='项目分类')),
            ],
        ),
    ]
