# Generated by Django 3.1.4 on 2021-01-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210112_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinfocategory',
            options={'verbose_name': '项目多对多中间表', 'verbose_name_plural': '项目多对多中间表'},
        ),
        migrations.AlterModelTable(
            name='projectinfocategory',
            table='tb_ProjectInfoCategory',
        ),
    ]
