# Generated by Django 3.1.4 on 2021-01-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210112_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfocategory',
            old_name='baseinfo',
            new_name='baseInfo',
        ),
    ]
