# Generated by Django 3.1.4 on 2021-01-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210112_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategory',
            old_name='status',
            new_name='name',
        ),
        migrations.AddField(
            model_name='projectbaseinfo',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.projectcategory', verbose_name='状态外键'),
        ),
        migrations.DeleteModel(
            name='ProjectInfoCategory',
        ),
    ]
