# Generated by Django 3.1.4 on 2021-01-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210112_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebaseinfo',
            name='file_project',
            field=models.ForeignKey(help_text='项目阶段', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.projectbaseinfo', verbose_name='文档隶属项目阶段'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
