# Generated by Django 3.1.4 on 2021-01-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
        ('pages', '0022_auto_20210114_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebaseinfo',
            name='flow_name',
            field=models.ForeignKey(blank=True, help_text='流程对象', null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.flowmodel', verbose_name='流程对象'),
        ),
    ]
