# Generated by Django 3.1.4 on 2021-01-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_filebaseinfo_flow_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebaseinfo',
            name='flow_name',
        ),
    ]
