# Generated by Django 3.1.4 on 2021-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
