# Generated by Django 3.1.4 on 2021-01-18 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.UUIDField(default=uuid.uuid4, help_text='节点id', verbose_name='节点id')),
                ('node_name', models.CharField(help_text='节点名称', max_length=200, verbose_name='节点名称')),
                ('Flower', models.ForeignKey(help_text='审批人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '流程节点表',
                'verbose_name_plural': '流程节点表',
                'db_table': 'tb_flownode',
            },
        ),
        migrations.CreateModel(
            name='FlowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_no', models.CharField(default=uuid.uuid4, help_text='流程号', max_length=200, verbose_name='流程号')),
                ('flow_name', models.CharField(max_length=200, verbose_name='流程名称')),
                ('node', models.ForeignKey(help_text='节点', on_delete=django.db.models.deletion.CASCADE, to='approval.flownodemodel', verbose_name='节点')),
            ],
            options={
                'verbose_name': '流程表',
                'verbose_name_plural': '流程表',
                'db_table': 'tb_flow',
            },
        ),
    ]
