# Generated by Django 3.1.4 on 2021-01-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmodel',
            name='flow_no',
            field=models.CharField(default='065894', help_text='流程号', max_length=200, verbose_name='流程号'),
        ),
    ]
