# Generated by Django 3.1.4 on 2021-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20210120_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='flownodemodel',
            name='flow_no_node',
            field=models.CharField(help_text='流程号', max_length=50, null=True, verbose_name='流程号'),
        ),
        migrations.AlterField(
            model_name='flowmodel',
            name='flow_no',
            field=models.CharField(default='f005356', help_text='流程号', max_length=200, verbose_name='流程号'),
        ),
    ]
