# Generated by Django 3.1.4 on 2021-01-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20210121_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='任务名', max_length=200, verbose_name='任务名')),
                ('style', models.CharField(help_text='任务', max_length=100, null=True, verbose_name='任务类型')),
                ('status', models.CharField(help_text='任务状态', max_length=100, null=True, verbose_name='任务状态')),
            ],
            options={
                'verbose_name': '任务表',
                'verbose_name_plural': '任务表',
                'db_table': 'tb_task',
            },
        ),
        migrations.AlterField(
            model_name='flowmodel',
            name='flow_no',
            field=models.CharField(default='f985707', help_text='流程号', max_length=200, verbose_name='流程号'),
        ),
    ]
