# Generated by Django 3.1.4 on 2021-01-27 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0005_auto_20210126_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='update_time',
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(help_text='指定截止时间', null=True, verbose_name='指定截止时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='handle_time',
            field=models.DateTimeField(help_text='承接时间', null=True, verbose_name='承接时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='handler',
            field=models.CharField(help_text='处理人', max_length=50, null=True, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='task',
            name='leaders',
            field=models.ForeignKey(help_text='发布人', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='指定截止时间', verbose_name='指定开始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowmodel',
            name='flow_no',
            field=models.CharField(default='f729844', help_text='流程号', max_length=200, verbose_name='流程号'),
        ),
    ]
