# Generated by Django 3.1.4 on 2021-01-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_auto_20210127_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowmodel',
            name='flow_no',
            field=models.CharField(default='f836631', help_text='流程号', max_length=200, verbose_name='流程号'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(help_text='指定截止时间', null=True, verbose_name='指定开始时间'),
        ),
    ]
