# Generated by Django 3.1.4 on 2021-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_remove_filebaseinfo_flow_name'),
        ('approval', '0007_auto_20210127_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flownodemodel',
            name='Flower',
        ),
        migrations.AddField(
            model_name='task',
            name='degree',
            field=models.CharField(choices=[('info', '一般'), ('warning', '警告'), ('error', '严重'), ('critical', '非常严重')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.CharField(help_text='隶属项目阶段', max_length=20, null=True, verbose_name='隶属项目阶段'),
        ),
        migrations.DeleteModel(
            name='FlowModel',
        ),
        migrations.DeleteModel(
            name='FlowNodeModel',
        ),
    ]
