# Generated by Django 3.1.4 on 2021-01-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('approval', '0009_approvalbaseinfo_approvalleaders_approvalmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='handler_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='选择团队'),
        ),
    ]
