# Generated by Django 3.1.4 on 2021-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0010_task_handler_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='任务描述', null=True, verbose_name='任务描述'),
        ),
    ]
